"""
Agent system prompts package.
"""

from app.agent.prompts.system_prompts import (
    FINAGENT_SYSTEM_PROMPT,
    MARKET_DATA_ANALYST_PROMPT,
    TECHNICAL_ANALYST_PROMPT,
    FUNDAMENTAL_ANALYST_PROMPT,
    QUANT_STRATEGIST_PROMPT,
    RISK_ANALYST_PROMPT,
    NEWS_ANALYST_PROMPT,
    INDUSTRY_RESEARCHER_PROMPT,
)

# Create aliases for backward compatibility
MARKET_DATA_AGENT_PROMPT = MARKET_DATA_ANALYST_PROMPT
TECHNICAL_AGENT_PROMPT = TECHNICAL_ANALYST_PROMPT
FUNDAMENTAL_AGENT_PROMPT = FUNDAMENTAL_ANALYST_PROMPT
QUANT_AGENT_PROMPT = QUANT_STRATEGIST_PROMPT
RISK_AGENT_PROMPT = RISK_ANALYST_PROMPT
NEWS_AGENT_PROMPT = NEWS_ANALYST_PROMPT
INDUSTRY_AGENT_PROMPT = INDUSTRY_RESEARCHER_PROMPT

__all__ = [
    # General prompt
    "FINAGENT_SYSTEM_PROMPT",
    # Original names
    "MARKET_DATA_ANALYST_PROMPT",
    "TECHNICAL_ANALYST_PROMPT",
    "FUNDAMENTAL_ANALYST_PROMPT",
    "QUANT_STRATEGIST_PROMPT",
    "RISK_ANALYST_PROMPT",
    "NEWS_ANALYST_PROMPT",
    "INDUSTRY_RESEARCHER_PROMPT",
    # Aliases
    "MARKET_DATA_AGENT_PROMPT",
    "TECHNICAL_AGENT_PROMPT",
    "FUNDAMENTAL_AGENT_PROMPT",
    "QUANT_AGENT_PROMPT",
    "RISK_AGENT_PROMPT",
    "NEWS_AGENT_PROMPT",
    "INDUSTRY_AGENT_PROMPT",
]
